version: '3.9'
services:
  lenv:
    image: xanmarta/lenv
    volumes:
      - lenv_data:/data
    environment:
      - PUBLIC_KEY=${PUBLIC_KEY}
    ports:
      - "2222:22"

volumes:
  lenv_data: {}
